version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: backend-p4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p4_backend
      MYSQL_USER: mf
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge